ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.15
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    odom0: /odom
    odom0_config: [
      false,  # x
      false,  # y
      false,  # z
      false,  # roll
      false,  # pitch
      false,  # yaw
      true,   # vx
      false,  # vy
      false,  # vz
      false,  # vroll
      false,  # vpitch
      true,   # vyaw
      false,  # ax
      false,  # ay
      false   # az
    ]

    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 5

    imu0: /imu/data_raw
    imu0_config: [
      false,  # x
      false,  # y
      false,  # z
      false,  # roll
      false,  # pitch
      false,  # yaw
      false,  # vx
      false,  # vy
      false,  # vz
      false,  # vroll
      false,  # vpitch
      true,   # vyaw
      false,  # ax
      false,  # ay
      false   # az
    ]

    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 5