[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit BNO055 @ ^1.6.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    Wire

build_flags =
    -L .pio/libdeps/esp32dev/micro_ros_arduino/src/esp32/
    -l microros